package views;

import javax.swing.JOptionPane;
import persistence.Login;
import persistence.LoginRegisterDao;
import persistence.GamesRegisterDao;

public class LoginRegisterView extends javax.swing.JFrame {

    public LoginRegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnConsult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblUser.setText("User");
        getContentPane().add(lblUser);
        lblUser.setBounds(40, 60, 110, 16);

        lblPassword.setText("Password");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(40, 110, 70, 16);

        lblConfirmPassword.setText("Confirm Password");
        getContentPane().add(lblConfirmPassword);
        lblConfirmPassword.setBounds(40, 160, 110, 16);

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtUser);
        txtUser.setBounds(190, 60, 160, 22);
        getContentPane().add(txtConfirmPassword);
        txtConfirmPassword.setBounds(190, 160, 160, 22);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(190, 110, 160, 22);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(60, 230, 72, 22);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(160, 230, 72, 22);

        btnConsult.setText("Consult");
        btnConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsult);
        btnConsult.setBounds(260, 230, 75, 22);

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    public void clean() {
    
        txtUser.setText("");
        txtPassword.setText("");
        txtConfirmPassword.setText("");
    
    }
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        Login login;
        LoginRegisterDao loginDao;
        boolean result;
        
        login = new Login();
        login.setUser(txtUser.getText());
        
        loginDao = new LoginRegisterDao();
        result = loginDao.Connect();
        
        if(result == true) {
        
            result = loginDao.delete(login);
            
            if(result == true) {
            
                JOptionPane.showMessageDialog(null, "Game Deleted!!!");
            
            } else {
            
                JOptionPane.showMessageDialog(null, "Error when try to delete!");
                }
            } else {
                    
                    JOptionPane.showMessageDialog(null, "Connection Error!!!");
                    
                }
            
        clean();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        Login login;
        LoginRegisterDao loginDao;
        boolean result;
        
        login = new Login();
        login.setUser(txtUser.getText());
        login.setPassword(txtPassword.getText());
        login.setConfirmPassword(txtConfirmPassword.getText());        
        
        loginDao = new LoginRegisterDao();
        result = loginDao.Connect();
        
        if(result == true) {
        
            result = loginDao.update(login);
            
            if(result == true) {
            
                JOptionPane.showMessageDialog(null, "Updated Data!");
                
            } else {
            
                JOptionPane.showMessageDialog(null, "Save Error!!!");
            
            }
        } else {
         
            JOptionPane.showMessageDialog(null, "Connection Error!!!");
            
        }
        
        clean();
               
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultActionPerformed
        
        Login login;
        LoginRegisterDao loginDao;
        boolean result;
        String user;
        
        user = txtUser.getText();
        
        loginDao = new LoginRegisterDao();
        result = loginDao.Connect();
        
        if(result == true) {
        
            login = loginDao.consult(user);
            
            if (login != null) {
            
                txtUser.setText(login.getUser());
                txtPassword.setText(login.getPassword());
                txtConfirmPassword.setText(login.getConfirmPassword());
            
            } else {
            
                JOptionPane.showMessageDialog(null, "Game not found!");
            
            } 
            
        } else {
            
                    JOptionPane.showMessageDialog(null, "Connection Error!");
                    
            }
        
    }//GEN-LAST:event_btnConsultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsult;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
